# Generated by Django 5.2.13 on 2026-04-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adminprofilemodel',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='doctorprofilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctorprofilemodel',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='patientprofilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientprofilemodel',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='staffprofilemodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='staffprofilemodel',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
