# Generated by Django 5.2.13 on 2026-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_adminprofilemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofilemodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofilemodel',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofilemodel',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
