# Generated by Django 5.2.13 on 2026-04-25 20:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminprofilemodel_department_and_more'),
        ('appointmentsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentmodel',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctorprofilemodel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofilemodel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentmodel',
            unique_together={('doctor', 'date', 'time')},
        ),
        migrations.DeleteModel(
            name='PrescriptionModel',
        ),
    ]
