# Generated by Django 5.2.13 on 2026-04-25 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentsapp', '0002_alter_appointmentmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='reason_for_visit',
            field=models.TextField(blank=True, help_text='পেশেন্টের সমস্যার সংক্ষিপ্ত বিবরণ'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text='পেশেন্টের লক্ষণসমূহ')),
                ('diagnosis', models.TextField(help_text='রোগ নির্ণয়')),
                ('medicines', models.TextField(help_text='ঔষধের তালিকা (JSON বা ফরম্যাটেড টেক্সট)')),
                ('advice', models.TextField(blank=True, help_text='ডাক্তারের বিশেষ উপদেশ')),
                ('follow_up_date', models.DateField(blank=True, help_text='পরবর্তী সাক্ষাতের তারিখ', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointmentsapp.appointmentmodel')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
    ]
