# Generated by Django 5.2.13 on 2026-04-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminprofilemodel_department_and_more'),
        ('doctorsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailabilitymodel',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Doctor Availability', 'verbose_name_plural': 'Doctor Availabilities'},
        ),
        migrations.AddField(
            model_name='doctoravailabilitymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailabilitymodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='ডাক্তার কি এই সময়ে চেম্বারে বসবেন?', null=True),
        ),
        migrations.AddField(
            model_name='doctoravailabilitymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctoravailabilitymodel',
            name='day',
            field=models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctoravailabilitymodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='accounts.doctorprofilemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilitymodel',
            unique_together={('doctor', 'day', 'start_time', 'end_time')},
        ),
    ]
