# Generated by Django 5.2.13 on 2026-04-27 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ragapp', '0002_initial'),
        ('accounts', '0004_alter_adminprofilemodel_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorembeddingmodel',
            options={'verbose_name': 'Doctor Embedding', 'verbose_name_plural': 'Doctor Embeddings'},
        ),
        migrations.AddField(
            model_name='doctorembeddingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorembeddingmodel',
            name='embedding_model',
            field=models.CharField(default='sentence-transformers/all-MiniLM-L6-v2', help_text='Which embedding model was used', max_length=100),
        ),
        migrations.AddField(
            model_name='doctorembeddingmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctorembeddingmodel',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Extra info like speciality, rating, experience', null=True),
        ),
        migrations.AddField(
            model_name='doctorembeddingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doctorembeddingmodel',
            name='content',
            field=models.TextField(help_text='Doctor profile + reviews combined text for embedding'),
        ),
        migrations.AlterField(
            model_name='doctorembeddingmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='accounts.doctorprofilemodel'),
        ),
        migrations.AlterField(
            model_name='doctorembeddingmodel',
            name='embedding_vector',
            field=models.JSONField(blank=True, help_text='Optional: store embedding vector (FAISS হলে না রাখলেও চলে)', null=True),
        ),
        migrations.AddIndex(
            model_name='doctorembeddingmodel',
            index=models.Index(fields=['doctor'], name='Ragapp_doct_doctor__bd1ea4_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorembeddingmodel',
            index=models.Index(fields=['is_active'], name='Ragapp_doct_is_acti_ed0ef2_idx'),
        ),
    ]
