# Generated by Django 5.2.13 on 2026-04-25 21:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import patientsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminprofilemodel_department_and_more'),
        ('patientsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecordmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Medical Record', 'verbose_name_plural': 'Medical Records'},
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_records', to='accounts.doctorprofilemodel'),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='document',
            field=models.FileField(blank=True, help_text='ডকুমেন্টের স্ক্যান কপি আপলোড করুন (PDF, JPG, PNG)', null=True, upload_to=patientsapp.models.patient_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='record_type',
            field=models.CharField(choices=[('GENERAL', 'General Checkup'), ('REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('SURGERY', 'Surgery Record'), ('IMMUNIZATION', 'Immunization')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, help_text='রেকর্ডের একটি সংক্ষিপ্ত শিরোনাম (যেমন: Blood Test Report)', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecordmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecordmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.patientprofilemodel'),
        ),
    ]
