# Generated by Django 5.2.13 on 2026-04-27 17:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminprofilemodel_department_and_more'),
        ('reviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Only verified reviews will be used in AI recommendation'),
        ),
        migrations.AddField(
            model_name='reviewmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='comment',
            field=models.TextField(help_text='Patient feedback about the doctor'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.doctorprofilemodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.patientprofilemodel'),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(help_text='Rating must be between 1 and 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='reviewmodel',
            unique_together={('patient', 'doctor')},
        ),
    ]
